### ISSUE TITLE
Screenshot does not appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.freac.freac#1]
![captura de tela de 2018-12-21 11-02-04](https://user-images.githubusercontent.com/26097419/50343922-9a1ccf00-0507-11e9-8221-29e171e3c63b.png)

**Comment by enzo1982** [comment]
Looks like the build server has issues loading the screenshots from freac.org. I put them on GitHub and they now show up in Software Center:

![software-center](https://user-images.githubusercontent.com/7796713/51426326-71145a80-1be9-11e9-8332-7fa6f7e7faa8.png)

The Flathub website is not updated yet, but once it is, the screenshots should appear there as well.
