### ISSUE TITLE
MAC codec no longer available

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.freac.freac#3]
Seems that the creator of MAC doesn't like having old libraries versions around. I've looked into it and the newest version is here:
https://monkeysaudio.com/files/MAC_SDK_538d.zip

The mac.patch is also backwards compatible

**Comment by enzo1982** [comment]
Yes, that happened a few times before. The original package is still available at: http://freac.org/patches/MAC_SDK_533.zip

I won't update the recipe here between releases, but next time I'll refer to the MAC package on freac.org instead.

**Comment by Eonfge** [comment]
Sound good to me.

Just so you know, I share some items form your manifest with Asunder and Flacon.
https://github.com/flathub/ca.littlesvr.asunder/blob/master/ca.littlesvr.asunder.yaml
https://github.com/flathub/com.github.Flacon/blob/master/com.github.Flacon.yaml

Would it be interesting to you to add these to a shared module? We could make a mac and a musepack module to share some of the work.

**Comment by Eonfge** [comment]
Totally resolved now. Good teamwork
